require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/users/settings", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Users::Setting. As you add validations to Users::Setting, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Users::Setting.create! valid_attributes
      get users_settings_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      setting = Users::Setting.create! valid_attributes
      get users_setting_url(setting)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_users_setting_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      setting = Users::Setting.create! valid_attributes
      get edit_users_setting_url(setting)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Users::Setting" do
        expect {
          post users_settings_url, params: { users_setting: valid_attributes }
        }.to change(Users::Setting, :count).by(1)
      end

      it "redirects to the created users_setting" do
        post users_settings_url, params: { users_setting: valid_attributes }
        expect(response).to redirect_to(users_setting_url(Users::Setting.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Users::Setting" do
        expect {
          post users_settings_url, params: { users_setting: invalid_attributes }
        }.to change(Users::Setting, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post users_settings_url, params: { users_setting: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested users_setting" do
        setting = Users::Setting.create! valid_attributes
        patch users_setting_url(setting), params: { users_setting: new_attributes }
        setting.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the users_setting" do
        setting = Users::Setting.create! valid_attributes
        patch users_setting_url(setting), params: { users_setting: new_attributes }
        setting.reload
        expect(response).to redirect_to(users_setting_url(setting))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        setting = Users::Setting.create! valid_attributes
        patch users_setting_url(setting), params: { users_setting: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested users_setting" do
      setting = Users::Setting.create! valid_attributes
      expect {
        delete users_setting_url(setting)
      }.to change(Users::Setting, :count).by(-1)
    end

    it "redirects to the users_settings list" do
      setting = Users::Setting.create! valid_attributes
      delete users_setting_url(setting)
      expect(response).to redirect_to(users_settings_url)
    end
  end
end
